### ISSUE TITLE
Compile clobbers existing directories

### ISSUE THREAD

**Issue by kristoferjoseph** [sintaxi/harp#14]
# Compile clobbers existing directories
## Steps to reproduce
1. Create a directory ( let's call it blog ) and put some content in it... say a .git folder, .gitignore
2. Run `harp init` in this folder ( possibly in a src directory )
3. Run `harp compile --output /path/to/blog` 
## Expected results

Static files generated into the blog directory ( root of project )
## Actual results

Directory is clobbered instead of added to losing any content you had in it

**Comment by bradcliffe** [comment]
Not sure if I'm doing something wrong, but it looks like there's still some behavioral issues on this one. I'm writing `harp compile _harp ./` at the root of my project, but it's wiping out existing files. I have to recreate my CNAME record for Github Pages each time I want to push recompiled changes to my site.

**Comment by joshuairl** [comment]
I have an interesting use-case that I was curious if there was a way to handle it...
I have a client that still uses SVN and has static html, css, js, etc.

I've been doing work for them and I decided to throw it all in Harp and compile it out.
But they don't want to use Harp or anything else right now just due to umm.... I don't want to say stubbornness to try new things...

But they're still on SVN, and I'm wanting to manage the harp.js version in my own git repository.
I'd like to be able to do like `harp compile ./ ../otherrepo-svn/` but have it ignore the ".svn" directory so it doesn't clobber the working copy logic.

I wish there was just a simple ".harp-ignore" or something that I could use and prevent it from worrying about .svn in that other folder.
