### ISSUE TITLE
cache-control header for static assets

### ISSUE THREAD

**Issue by pgte** [sintaxi/harp#276]
Is there a way to control the response cache-control header for static assets?

**Comment by edmorley** [comment]
Having a Cache-Control or Expires header is essential, since browsers fall back to their own algorithms otherwise, which mean files can be cached for 24 hours or 10% of the time since Last-Modified, see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching_FAQ
http://tools.ietf.org/html/rfc2616#section-13.2.4

This has caught us out in the past (using Apache), since whilst our static assets were revisioned with SHA filenames, the html files that referred to them were being over-cached.

For me at least, not having this ability is a blocker to using Harp.

**Comment by isaacrg** [comment]
From what I am aware, a temporary fix, would be to use Harp as middleware in an express app, with the header declared in self-written middleware. This gives you cache-control options, alongside allowing you to add custom dynamic page, authorisation, etc.

It would be great if these options were configurable, but using express to intervene isnt too messy.
