### ISSUE TITLE
Better Blog Support

### ISSUE THREAD

**Issue by mike-ward** [sintaxi/harp#356]
I really like the convention based approach of Harp. While blogs can be done with _data.json, it's more friction than I would like. What about the following:
- _posts is a special folder (or specified in the config) that contains blog posts.
- files with the name format YYYY-MM-DD-Slug.md are read as blog posts.
- Date and slug come from file name.
- The first non space line in the *.md file is the title of the post (no YAML).
- The layout used is the one in the _posts folder or parent, etc. if not found.
- An object is exposed in the data model to reference posts in templates

Thoughts? I'm also volunteering to write this if a design can be agreed upon.

**Comment by victorsegall** [comment]
The idea is sound in identifying a pain point, and the grunt-harp-post approach is cool. At the root of it, _data.json is still the right way. That's about data de-duplication, which argues against the file naming convention of YYYY-MM-DD prefixed.

As a user, this isn't a matter of difficulty, but is one of ergonomics. I can write in JS (hackishly), and JSON is dead easy, but I'll want to avoid that mid-stride of writing prose.

Designing that away would be a good thing, because it's separating scope. You want to think about page layout, markup, and data structures when building your site, but not when using it to publish.

I think that the answer is what grunt-harp-post does, and building a _data.json from the contents of an "articles" directory.

Perhaps the file naming scheme could be made arbitrary, defined by regex, and given today's convention as the default. In that way, one could intentionally configure file name patterns that map to _data.json fields in Mike's way. That would get you "title" and "date created". Categories is a YAML-sized ball of wax.

**Comment by xHN35RQ** [comment]
> I wrote a couple of quick js scripts to gen and update the data.json file.

@mike-ward may I please see your scripts? I'm building a small-ish blog and found that I'd prefer to programatically generate my `_data.json` files - I'm looking for a simple way to add new blog posts that doesn't require me to hand-edit `_data.json` - many thanks!

**Comment by mike-ward** [comment]
I stopped using harp a while ago. The scripts I wrote are gone. Sorry.

**Comment by xHN35RQ** [comment]
Not a problem, I've found another way to solve my problem. thanks!
