### ISSUE TITLE
How would I ignore node_modules?

### ISSUE THREAD

**Issue by AndyF** [sintaxi/harp#393]
Compiling a project with `node_modules/` often results in conflict. Harp should ignore this by default (as there's no practical reason to do so), or give us the option to ignore via `.gitignore`.

**Comment by urbildpunkt** [comment]
You should always add the `node_modules` directory to your `.gitignore`, but the best way to avoid running into a compiling issue is to structure your project using the [public directory](http://harpjs.com/docs/development/public) and keeping `node_modules` outside of it. That way Harp won't try to compile it.

But it seems like it would be a useful feature to expand the ignore functionality of Harp so that you never have to worry about how you structure you dependencies.

**Comment by kennethormandy** [comment]
Thanks for answering this, @urbildpunkt. We haven’t forgotten about this and just want to make sure we commit to the right solution.

I’m going to close this in favour of #275, but feel free to add suggestions there.

If someone’s able to get all the tests to pass on #312, I think we might be able to merge that sooner. Otherwise, it’ll be something that gets figured out later on.

**Comment by stoplion** [comment]
I have my node_modules outside of public folder and it still get compiled in the www folder. Is there a way to make this not happen?
