### ISSUE TITLE
@import url Sass error

### ISSUE THREAD

**Issue by stoplion** [sintaxi/harp#397]
In main.sass when trying to @import Google fonts, instead of making http call for font it looks for file.
```
@import url("http://fonts.googleapis.com/css?family=Merriweather:400,300,700,900")
@import url("http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,700,300,600,800,400")
```

Error:
`Sass -> CSS (file to import not found or unreadable)`

**Comment by kennethormandy** [comment]
That just got fixed in Libsass (which we use for parsing Sass files) two weeks ago https://github.com/sass/libsass/pull/822, we’ll be able to include it once they’ve tagged a new version. Thanks for opening an issue!

In the meantime you should be able to include them using Google Fonts `<link>` or `<script>` snippet options.

**Comment by stoplion** [comment]
Thanks!
