### ISSUE TITLE
`harp compile -o ./` deletes all files in current directory

### ISSUE THREAD

**Issue by parkerault** [sintaxi/harp#400]
Reproduce
````
harp init my-project
cd my-project
harp compile -o ./
````
result: project files are deleted :open_mouth: 

I understand this isn't a normal use case, but anything that lets a user unknowingly `rm -rf` a directory is pretty dangerous.

**Comment by kennethormandy** [comment]
Thanks for opening an issue, this is definitely a bug. My sincere apologies if this happened to your project. We have a number of guards in place to stop this from happening, and I’m not sure why this situation isn’t one of them—I’m looking into it now.

**Comment by sintaxi** [comment]
I don't disagree, but how else could it work? Open to suggestions.

@parkerault FWIW - there are protections in place to prevent you form deleting your home directory or any other parent directory.

**Comment by parkerault** [comment]
I agree it's a tricky problem. Perhaps a warning if the output directory isn't empty?
```
warning: All files in #{outputDir} will be deleted!
really continue? y/n
```
If that's problematic for build scripts you could add a `--force` flag to `harp compile`. It's a bit obnoxious, but it seems like the solution that would require the least amount of code.

P.S. Nothing of value was lost.

**Comment by silentrob** [comment]
Perhaps we could use the [trash module](https://www.npmjs.com/package/trash) instead of the more aggressive rm.

**Comment by sintaxi** [comment]
@silentrob hmm, not a bad idea.

**Comment by kevinsimper** [comment]
The same as #92

**Comment by josh-egan** [comment]
I got bit by this issue tonight. +1 to using the trash package. 

Although it could be considered a feature which encourages frequent commits. :wink:

**Comment by kennethormandy** [comment]
I’m really sorry about that @josh-egan. Not that it helps much right now, but I opened up a PR #449 for one approach, which prevents compiling into the source directory outright (when you have explicitly asked to compile into that directory rather than implicitly let Harp compile to `www/`).

Alternatively, we could treat `harp compile -o ./` as really meaning `harp compile -o ./www`, which is probably the expected behaviour?

**Comment by josh-egan** [comment]
Oh it's alright. Losing code's a bummer, but it's on me for not commiting my code. I've been making my most incremental commits ever since I lost that code last night. :smile: 

I'm brand new to harp, so I don't know what the behavior should be. I love convention over configuration, but one of the growing pains in a new environment is learning the conventions. A warning would have been nice. If I understand the effect of your PR correctly, would it cause the compile method to abort [here](https://github.com/sintaxi/harp/blob/release-v0.17.0/lib/index.js#L179)? If so, the [error message](https://github.com/sintaxi/harp/blob/release-v0.17.0/lib/index.js#L182) should probably be updated to reflect this new case.

In regards to making the compile call programmatically, another issue I ran into was understanding the parameters. My relevant code is as follows: 

```javascript
var gulp = require('gulp');
var harp = require('harp');

var paths = {
  projectDir: './',
  outputDir: './dist'
};

gulp.task('build', function (done) {
  harp.compile(paths.projectDir, paths.outputDir, done);
});
```

In trying to understand what compile was doing, I read through [the code](https://github.com/sintaxi/harp/blob/release-v0.17.0/lib/index.js#L145). A comment says that projectPath and outputPath are both optional, but  the way the code is written, the projectPath is required, and then the second argument becomes the callback if a third argument is not provided. If the callback is undefined then it blows up, so the callback is also required. Thus the outputPath is the only optional argument, and if the outputPath is included then the callback must also be included. I'm not totally familiar with the framework yet, so I'm not sure what it's supposed to do. I think it'd be nice if the code itself was more clear about what it requires. I'd be happy to help with a PR if I can get some insight into the intended behavior.
