### ISSUE TITLE
Harp won't install correctly

### ISSUE THREAD

**Issue by CourtneyDion** [sintaxi/harp#446]
After installing Harp with io.js, I get the following error anytime I call 'harp' in command line:

Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Courtney\AppData\Roaming\npm\node_modules\harp\node_modules\terraform\node_modules\node-sass\lib\index.js:14:15)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

**Comment by sintaxi** [comment]
This appears to be a compatibility issue between iojs and node-sass. iojs aims to be compatible with nodejs so the problem likely exists in iojs.

A few things that could help...
- What version of iojs are you using?
- What OS are you using?

**Comment by CourtneyDion** [comment]
io.js 2.0.0 (x64)
I'm running Windows 10 tech preview

**Comment by MisterY** [comment]
+1
io.js v2.0.1
Windows 7 x64

**Comment by kennethormandy** [comment]
Would either of you mind trying it with the latest stable release of Node instead so we know if it’s a Windows issue or an io.js issue? We can definitely investigate if it’s the former.

**Comment by CourtneyDion** [comment]
It installed fine with node, so it apparently an issue with iojs.

**Comment by MisterY** [comment]
Right. Works fine with Node, old and new.

**Comment by kennethormandy** [comment]
Okay, thanks for checking. Looks like this is sorted in Node-sass v3.0.0 proper, which just came out two days ago. We’re using a 3.0.0-beta.5 and will be upgrading it in the next release of [Terraform](http://github.com/sintaxi/terraform), Harp’s preprocessing engine.

Node-sass only contains a limited number of platform specific binaries, and otherwise it will try rebuilding them. In this case, you probably don’t have Visual Studio installed, which is unfortunately required to rebuild the binary on Windows (normally, this is a non-issue).

In the meantime, you could use [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) to update to Node-sass v3.0.0 if you want. Hope that’s helpful :)

**Comment by MisterY** [comment]
In my case the problem is that there are too many Visual Studio versions installed. A parameter `--msvs_version=2013` is needed in that case.
Anyway, I got past that point by manually building/installing node-sass from terraform directory.
The problem after that is that running `harp server` throws an error along the lines of "function not bound" or something similar. I'm back to running with Node again.

The tip for npm shrinkwrap is interesting. Will check it out. Thanks!

**Comment by sintaxi** [comment]
The 2.x.x io.js release likely represents a breakage of API which may mean incompatibility with NodeJS.
