### ISSUE TITLE
Postcss support.

### ISSUE THREAD

**Issue by iamfrntdv** [sintaxi/harp#451]
Hi! it would be great feature if harp could support postcss. is there any way to integrate postcss with harp?

**Comment by ai** [comment]
[PostCSS](https://github.com/postcss/postcss) support will brings a Autopefixer support. For example, Google [recommends](https://developers.google.com/web/fundamentals/tools/build/setupbuildprocess#dont-trip-up-with-vendor-prefixes) Autoprefixer as a only way to handle vendor prefixes.

/cc @kennethormandy @sintaxi

**Comment by kennethormandy** [comment]
Hey! Thanks for opening an issue. We actually already have [Autoprefixer support built in](http://harpjs.com/blog/v0-14-0-implicit-autoprefixing), definitely agree it is the best way to approach that.

While I don’t think we’d be totally opposed to adding PostCSS, I have a hard time imagining how it would work. Harp tries to limit the amount of configuration you have to do, and to my (admittedly limited) knowledge of PostCSS, isn’t there almost always something you have to configure or determine about how you want the syntax to work?

I could see @sintaxi being interested in an Sass compatible version of PostCSS to avoid having to distribute the libsass binaries however.

**Comment by ai** [comment]
@kennethormandy yeap, PostCSS runner need a plugins array as a config. Like:

```js
postcss: [
    require('autoprefixer')({ browsers: ['last 2 versions'] }),
    require('cssnext')
]
```

**Comment by sintaxi** [comment]
Looks pretty nice. Pardon the rudimentary question, but what problem does postcss solve which isn't solved with scss?

**Comment by ai** [comment]
@sintaxi you can do muuuuch more with PostCSS which is impossibe with Sass:

* Autoprefixer
* [cssnext](http://cssnext.io/) is like a Babel for CSS. You write a CSS4 and it will compile it to CSS3.
* [doiuse](https://github.com/anandthakker/doiuse) linter to test your CSS by Can I Use.
* [rtlcss](https://github.com/MohammadYounes/rtlcss) to create a mirror design for Arabic/Hebrew versions
* [postcss-style-guide](https://github.com/morishitter/postcss-style-guide) to generate components style guide automatically bby your CSS
* [postcss-data-packer](https://github.com/Ser-Gen/postcss-data-packer) to move all base64 inlined images to separated file

I can write [many other plugins](https://github.com/postcss/postcss#plugins), that are impossible at Sass, but these are my favorite.

**Comment by admdh** [comment]
and as i know it is much faster than any of other existing css pre-processors. it is written in javascript and all plugins too, so there is a huge possibility of setting it up with custom plugins..

and it would be great if there was harp support so it could be used with any node.js app!

**Comment by kennethormandy** [comment]
PostCSS looks very cool, and those are some awesome examples, thanks. Still, I don’t know if it is a good fit with Harp (at least until we had some larger language plugin system #209). Harp specifically tries to avoid making you think about the kind of configuration that is a feature of PostCSS. We intentionally don’t even expose configurations for LESS or EJS for example.

That said, cssnext seems like the most natural fit if we were going to have some kind of PostCSS option, and we do have a PR for Babel open, which could pair nicely with it I suppose.

**Comment by admdh** [comment]
i agree with you that frameworks, plugins modules should stay simple and easy configured but at the same time there should be a option to add more configurations because they all written in some programming languages and it's a pity not to use all power of programming languages in our case javascript. On the other side there are always a lot of desktop apps that are easy configured...

What i would like to say with this?
A beginner in most cases will always start with some app because they are easy configured. When/If he levels up, he will switch from app to coding itself because there are much more flexible configurations which will satisfy his wishes.

Harp is a great tool and it would be great if it could support PostCSS. Harp still can stay simple with LESS or SASS (for beginners or for those who just prefer LESS or SASS) but at the same time more configurable and more complex with PostCSS (for those who would like to use more complex and configurable toys))).

**Comment by admdh** [comment]
Hey guys, sorry for disturbing you! i just would like to know your finale thought about adding PostCSS to harp. Is it possible or you would like to keep Harp without PostCSS support? Thank you!

**Comment by igorshubovych** [comment]
As far as I understood all processing is done in terraform:
https://github.com/sintaxi/terraform

Terraform is very opinionated (which is good), but you even currently configure Autoprefixer:
https://github.com/sintaxi/terraform/blob/master/lib/stylesheet/index.js#L63

This makes people creating tickets like this: #472.

@ai,
There is almost no configuration in harp. To configure PostCSS you need to define the flow of plugins, which is hard in JSON form. Also terraform has to require all of plugins, which I doubt they will do.
Maybe if CSSNext or CSSNano is widely adopted, they can include support for these set of plugins.

**Comment by gillchristian** [comment]
I agree with the idea of Harp being no-configuration based, and I love it. But I would not mind to have the option, say in the `harp.json` file, to add PostCSS (or Babel pluings, since they were mentioned in the thread) to run. And since PostCSS will not change the output if no plugins are passed to it, there is no problem to just add it to the pipe.

I use PostCSS daily on my workflow and I would love to be able to use it with Harp.

**Comment by svicalifornia** [comment]
+1 for PostCSS support in Harp.

And I would also like to see more configuration options generally. Ruby's Middleman static generator is configurable via a Ruby config file, allowing a great deal of functionality and flexibility.

**Comment by stuartpb** [comment]
Whatever Autoprefixer rules Harp uses right now, they're not doing anything to adapt Flexbox properties (in fact, I don't see *any* prefixed properties in my output CSS). Is Harp's Autoprefixer just really out of date or something? Is it not processing files that already end in `.css`?

**Comment by Kukunin** [comment]
+1 for Postcss support, and at least opportunity to OPTIONALLY edit configuration files.
My use case is that I want to use tailwindcss, which is amazing, but it's available as a PostCSS plugin.
Since harp does not support PostCSS, nor it's configurable, I got to invent some hacky solutions
