### ISSUE TITLE
harp compile creates absolute path for css file

### ISSUE THREAD

**Issue by k5e** [sintaxi/harp#46]
How to reproduce:

```
% harp init myharpproject
% cd myharpproject
% harp compile
% cat www/index.html
  <!DOCTYPE html>
  <html>
    <head>
      <link rel="stylesheet" href="/css/main.css">
    </head>
    <body>
      <h1>Welcome to Harp</h1>
      <h3>This is yours to own. Enjoy.</h3>
    </body>
  </html>
% _
```

(Line breaks added by me)

Open www/index.html in the browser -> the stylesheet cannot be found.

The URL of the stylesheet is absolute to the "document root" which is not necessarily the case and depends on where you deploy the app to.

Suggestion: replace the absolute URL with URL relative to index.html.

Best regards
Christian

**Comment by amitkeret** [comment]
I've encountered this problem as well.
Since I use Harp on a subdirectory, these links break. And if you change the path on `_layout.jade` to `href="css/main.css"`, it will break on any sub-pages anyway.

Thinking forward - why not use the `current` object to manipulate paths?
I tried writing a function/mixin of this, but I'm pretty new to Jade and couldn't get the syntax right... The idea, anyway, is to use the length of the `current.path` array to prepend `../` to links.

```jade
- function l(src) {
-   var p = '';
-   for (var i = 0; i < (current.path.length - 1); i++) {
-     p += '../';
-   }
-   return p + src;
- }

link(rel="stylesheet" href=l("css/main.css"))
```

**Comment by rossPatton** [comment]
Having this same issue.

Scenario: created a repo that will be used for one-off art directed articles. wanted to use a static site generator to easily scaffold out these projects but still allow lots of flexibility. each article is created with `harp init article-name`. however `harp server` and `harp compile` is outputting an incorrect css url (/main.css instead of just main.css).
