### ISSUE TITLE
Harp should redirect links with extensions

### ISSUE THREAD

**Issue by btakita** [sintaxi/harp#468]
Hello, I have a site using markdown with internal links using "*.md", to work from Github.

Unfortunately, these links point to 404 pages when being served from harp.

Is there a way for harp to redirect "*.md" pages to the html equivalent?

**Comment by jdcauley** [comment]
@btakita I'm a little confused are you trying to server html or md pages and is this before or after compile?

**Comment by KamranAsif** [comment]
I am having this issue as well. I'm trying to serve markdown files that have links to other markdown files.

e.g. [Some Link ](foo/bar.md)

This normally causes the browser to point to http://localhost:9000/foo/bar.md, but harp doesn't understand that I'm looking for the html equivalent. 

Is there a way to have harp understand http://localhost:9000/foo/bar.md as http://localhost:9000/foo/bar.html?

**Comment by alfonso-presa** [comment]
Might be related to this one:
https://github.com/sintaxi/harp/issues/604

**Comment by StingyJack** [comment]
@misterhtmlcss - I don't use this program anymore, but are you closing this and #604 because it's fixed?

**Comment by misterhtmlcss** [comment]
More likely it's due to age and issue bankruptcy. We needed to clear the issues from the past as it would have taken hours to determine which is what and where.

If it's currently an issue people - we hope - will kindly remind us. 

We just had too many old issues to get through individually. Sorry if this caught you by surprise. 

Thank you for saying hi though. :))
