### ISSUE TITLE
Clarify harp's compass abilities

### ISSUE THREAD

**Issue by rocketnova** [sintaxi/harp#471]
Hey there, I've been trying to figure out what (if any) support harp has for compass. For instance, what is the best way for me to use compass/typography/vertical_rhythm in my harp projects?

I poked around in the harp and terraform issues to try to find something relevant, but the closest thing I could find was #113 which is pretty old and happened before compass stopped being ported to libsass (https://github.com/Compass/compass/issues/1916#issuecomment-95638618).

It looks like harp is using node-sass. Is there any support for https://github.com/sass-eyeglass/eyeglass?

**Comment by kennethormandy** [comment]
Hey, a while back we [modified Compass](https://github.com/harp/compass) to work with Node-sass/Libsass which should still work but we aren’t actively maintaining now. The Ruby-based Compass stuff will never work with Harp since we didn’t want to impose a Ruby dependency just for that (I am not sure if the Vertical Rhythm mixin falls into this category or not).

Eyeglass is something I’m personally interested in, and I will probably look at what it would take to add it to Harp in the future. It’s too early right now though.

Hopefully that is helpful!

**Comment by rocketnova** [comment]
@kennethormandy Ah very helpful. Thanks! I assume that since you say that [your modified version of compass](https://github.com/harp/compass) should still currently work, it's being included in harp. Is there a roadmap for what will happen to your version of compass?

**Comment by kennethormandy** [comment]
It’s not being included in Harp proper, but you can still install that Component or just drop the source files into your own project if you’d like. There’s no roadmap for it, it’s not actively maintained because Compass isn’t either. It turned out to be impractical to maintain these components separately, now we just support whatever works with Node-sass. For Compass, that means we should be able to support the Eyeglass version in the farther future, and in the meantime my legacy modified version should work.

If you aren’t set on Compass, however, I’d highly reccomend something Node-sass compatible like Bourbon & Neat or Foundation instead.

**Comment by rocketnova** [comment]
Awesome. Thanks for clarifying and for the additional information! It really helps as I start to dig into Harp.
