### ISSUE TITLE
Use a different sass implementation?

### ISSUE THREAD

**Issue by isaacrg** [sintaxi/harp#511]
I know this is an extreme idea, and I am merely fielding for views. What would hyou all think of the idea of using a non-official sass implementation, perhaps one which is compiled to pure JS, like [medialize/sass.js](https://github.com/medialize/sass.js). That particular module compiles libsass with emcriptem, meaning that the current troubles that people are having (re: #510, previously #474, [et al](https://github.com/sintaxi/harp/issues?utf8=%E2%9C%93&q=is%3Aissue+libsass+)) would likely be resolved.

**This could reduce performance significantly**, but I still think it merits discussion given the existing problems with node-sass people are experiencing.

**Comment by kennethormandy** [comment]
Performance has always been a big concern for this project, to the point that we even benchmarked the preprocessors at one point. I don’t think we’d opt-into a slower one, since that was part of the reason (speed and dependency overhead) that we never used Ruby Sass in the first place, even when it Node-sass was not nearly as stable as it is now.

I think the real problem with all of those issues is that we don’t have the ability to release updates of Harp as quickly as some people adopt new releases of Node.js or IO.js, which causes problems with the Node-sass binaries. Hopefully this will change in the future, but in the short term people can always `npm install --save-dev node-sass@latest` or run `npm shinkwrap` on their project and update Node-sass themselves.

We’ll definitely have Node-sass at the latest version in the next release, and I think as Libsass is so close to parity with Ruby Sass now, things might slow down for a while. Hopefully that works for you, I appreciate you looking into other options! Perhaps in the future we’ll see a PostCSS implementation of Sass that passes the spec and then we could move to that.

**Comment by isaacrg** [comment]
I agree with you - I raisedI the issue out of intruige,  because Heroku is now spitting errors at me, because even heroku has been bumped up to Node version 5 - and I use harp in an application which I i need to keep constantly up.  I'll try and think of a solution, but currently we all seem to have to play catch up to a single upstream library. I'll close this, but I'd still happily hear views here, but this doesn't merit staying open.

**Comment by kennethormandy** [comment]
I would recommend setting your engines and pinning your dependencies if you haven’t already, I think that is where Heroku gets its version of Node from. If it’s missing maybe they default to the latest? I could be wrong, but they are still using v0.12.0 in their tutorial / example app.

**Comment by isaacrg** [comment]
They default to the latest stable version, and I previously hadn't set
mine. Heroku haven't updated their examples in ages.
