### ISSUE TITLE
Syntax Highlighting in Markdown

### ISSUE THREAD

**Issue by IngwiePhoenix** [sintaxi/harp#519]
It would be nice if we wouldn't need to drop HighlightJS into our static files, and instead can have it pre-rendered already.

HLJS takes up a _big_ bit of data. So it'd be nice if you could allow people to preprocess syntax highlight-able blocks during compilation.

**Comment by IngwiePhoenix** [comment]
Any news on the issue here?

**Comment by sarahlim** [comment]
@IngwiePhoenix I still need to write tests but plan on opening a PR within a couple days. In the interim, you can implement this easily in your local Harp installation (technically [Terraform](https://github.com/sintaxi/terraform), since that's what manages Harp's asset pipeline).

From Harp's package directory, checkout a new branch, install and save the `highlight.js` package from npm, and then modify `node_modules/terraform/lib/template/processors/md.js` by replacing the first line with the following:

```js
var marked = require("marked").setOptions(
  {
    langPrefix: 'language-',
    headerPrefix: '',
    highlight: function (code) {
      return require('highlight.js').highlightAuto(code).value;
    }
  })
```

You'll still need to include the Highlight.js CSS file in your layout template, but this should take care of the pre-processing.

**Comment by IngwiePhoenix** [comment]
Including the Highlightjs CSS is no biggie - its really small, so that works well for me.

Glad to hear you picked this up! Looking forward to the PR. :)

**Comment by kennethormandy** [comment]
We do have [this existing PR](https://github.com/sintaxi/terraform/pull/96), which would be nice to get a second opinion on. I think this would be a valuable addition to Terraform, but we never really got a chance to discuss it yet. In the meantime, [Prism](http://prismjs.com/) is also a really nice client side option, too.
