### ISSUE TITLE
Github Project Pages : Relative link fail

### ISSUE THREAD

**Issue by skang404** [sintaxi/harp#530]
If you're not using a CNAME and hosting your Project Page on GitHub Pages, it's served out of a "project-name" subfolder

```
http://user-name.github.com/project-name
```

 but relative url's fail. Eg: 

```
<link rel="stylesheet" href="/main.css">
```

resolves to 

```
http://user-name.github.com/main.css
```

whereas we expect, 

```
http://user-name.github.com/project-name/main.css
```

The trick is to define a custom variable in [global](http://harpjs.com/docs/development/globals) `_harp.json' file,

```
{
 "globals": {
    "baseurl": "/project-name"
    }
}
```

Note: starting forward slash & no ending slash.
Now we can insert this variable wherever there are relative urls. Eg:

```
link(rel="stylesheet" href="#{ baseurl }/main.css")
```

in `_layout.jade`.

But this brings us to another problem: urls are broken locally! 
When we run `harp server`, the browser will look for files under the root, i.e. `localhost/main.css` But, with Github Pages, what happens is this: `http://username.github.com/main.css`, while we want `http://username.github.com/project-name/main.css`... So now, local development is affected.

I think the solution is to define a new kind of `option` in `harp server [options]`,
where we could pass our globally defined variables & its value.

For example, we could use `harp server --baseurl ''` if we want to pass the value of `baseurl` global variable (which we had defined in `_harp.json`earlier) as empty(`''`).

Or any other workaround?

**Comment by skang404** [comment]
Also, I think this will close #293

**Comment by skang404** [comment]
I guess you should consider submitting a bug to github about this

**Comment by matteo-bombelli** [comment]
a good thing for that is to use relative path: use "../" to go up one level or "" [nothing] to stay in the same folder... so think you're building it with all the htmls pages in the main folder: you just need to use "css/main.css" instead of "/css/main.css"

if you use "/" it means the root of your website so if you have http://www.example.com/folder/index.html, using "/css/main.css" will result in "http://www.example.com/css/main.css".

The tricky part of using relative path is that you need to change urls based on the level of your page, but harp gives you the [current object](http://harpjs.com/docs/development/current).

if you use (sorry I'm italian ;) )

``` js
    var PathBase="";
    var numLivelli = current.path.length - 1;
    for (var i=0; i<numLivelli; i++){
        PathBase = PathBase + "../";
    }
``` 

`pathBase` will give you the right relative part...

I'm really extending a lot of the harp main functions and using that way you can create also multilingual sites (see my github page for future improvements :) )

**Comment by tay1orjones** [comment]
I found that instead of these options, it was easier to declare a production or development base url based off the `environment` variable, and put that url in my main `_layout.jade` file within a [base tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base). This allows every link to be expressed in a relative fashion, including asset links for css, js, etc. including links in partials and pages that use the master `_layout.jade` file.

From my `_layout.jade`:
```.jade
head
  if environment == "production" || environment == "development"
    if environment == "production"
      //- github pages (production) need the base url to be the
      //- path of the project repo
      base(href="/githubUserName/repositoryName/")
    if environment == "development"
      //- local dev environment (development) needs the base url
      //- to be a slash (for harp server)
      base(href="/")
  else
    //- alternatively, you can use the node env variable directly
    //- as the base url to compile to a custom url (ex. another
    //- user's fork's gh-pages branch)
    base(href="#{environment}")
```

Use the custom node env option by running
```bash
NODE_ENV=url/path/here harp compile
```
You can also do the same with the server
```bash
NODE_ENV=url/path/here harp server
```
It's a bit of a hack, but it works. Allows you to not have to prefix all urls with `#{baseurl}`

**Comment by Yajo** [comment]
I achieved the same while not being so hackish:

1. Add this to `harp.json` globals: `"rootPath": "$rootPath"`
1. Add this to `_layout.jade`: `base(href="#{rootPath}")`
1. Put the correct base depending on the environment.

Alternatively, you can use this jade:
```jade
    if rootPath !== undefined
      base(href="#{rootPath}")
    else
      base(href="/")
```

Which sets a default in case the variable is missing.
