### ISSUE TITLE
public

### ISSUE THREAD

**Issue by lukashl** [sintaxi/harp#537]
Hello

can I change folder 'public' to other ?

**Comment by kennethormandy** [comment]
Hey, currently no. In the next major release of Harp, we will be removing the `public` directory entirely, so Harp will always just serve the root. You can currently accomplish the same sort of thing by using the `_harp.json` file instead of a `harp.json` file: http://harpjs.com/docs/development/public …under the “root style applications” section

**Comment by lukashl** [comment]
Thx for fast answer
